from enum import Enum

class Err(str, Enum):
    OK = "OK"

    # ENV / CONFIG
    ENV_MISSING = "ERR-ENV-001"
    ENV_INVALID = "ERR-ENV-002"

    # BROKER
    SHOONYA_LOGIN_FAILED = "ERR-BROKER-001"
    SHOONYA_TIMEOUT = "ERR-BROKER-002"
    SHOONYA_RATE_LIMIT = "ERR-BROKER-003"
    SHOONYA_BAD_RESPONSE = "ERR-BROKER-004"

    # MARKET DATA
    DATA_EMPTY = "ERR-DATA-001"
    DATA_STALE = "ERR-DATA-002"

    # STRATEGY
    NO_SIGNAL = "ERR-STRAT-001"
    SIGNAL_INVALID = "ERR-STRAT-002"

    # EXECUTION
    ORDER_REJECTED = "ERR-EXEC-001"
    POSITION_MISMATCH = "ERR-EXEC-002"

    # SAFETY
    EMERGENCY_LOCKDOWN = "ERR-SAFE-001"
